ADVENTURE_DIRECTORY = {
    "book_of_heroes": {
        "series_name": "Book of Heroes",
        "heroes": {
            "Jaina": [
                "Arthas Menethil",
                "Antonidas",
                "Aegwynn",
                "Archmage Kalec",
                "The Lich King",
            ],
            "Rexxar": [
                "Leoroxx",
                "Warchief Blackhand",
                "Misha",
                "Ferocious Quilboar",
                "Lady Darkscale",
                "Khiragg",
                "Daelin Proudmoore",
                "Gorgrom the Dragon-Eater",
            ],
            "Garrosh": [
                "Greatmother Geyah",
                "Rehgar Earthfury",
                "Underqueen Zarzhet",
                "Seering Fire Elemental",
                "Cairne Bloodhoof",
                "Jaina Proudmoore",
                "Anduin Wrynn",
                "Thrall",
            ],
            "Uther": [
                "Alonsus Faol",
                "Orgrim Doomhammer",
                "Varok Saurfang",
                "The Dark Portal",
                "Blackrock Blademaster",
                "Venim Iceblade",
                "Mal'Ganis",
                "Prince Arthas",
            ],
            "Valeera": [
                "Hogger",
                "Edwin VanCleef",
                "Baron Revilgaz",
                "The Medics",
                "Trade Prince Gallywix",
                "Cho'Gall",
                "Garona Halforcen",
                "King Varian Wrynn",
            ],
            "Anduin": [
                "King Varian Wrynn",
                "Prophet Velen",
                "Archbishop Benedictus",
                "Valithria Dreamwalker",
                "Gul'dan",
                "Garrosh Hellscream",
                "Sylvanas Windrunner",
                "The Jailer",
            ],
            "Thrall": [
                "Durotan",
                "Draka",
                "Grommash Hellscream",
                "Orgrim Doomhammer",
                "Blackmoore",
                "Jaina Proudmoore",
                "Garrosh Hellscream",
                "Deathwing",
            ],
            "Gul'dan": [
                "Ner'zhul",
                "Cho'gall",
                "Blackhand",
                "Doomhammer",
                "Kil'jaeden",
                "Mannoroth",
                "Medivh",
                "Illidan Stormrage",
            ],
            "Malfurion": [
                "Cenarius",
                "Xavius",
                "Malfurion's Nightmare",
                "Azshara",
                "Mannoroth",
                "Archimonde",
                "Illidan Stormrage",
                "Ysera",
            ],
            "Illidan": [
                "Kurtrus Ashfallen",
                "Azshara",
                "Akama",
                "Maiev Shadowsong",
                "Kael'thas Sunstrider",
                "Malfurion Stormrage",
                "Sargeras",
                "Arthas",
            ],
            "Magni": [
                "Muradin Bronzebeard",
                "Moira Bronzebeard",
                "Ragnaros",
                "Nefarian",
                "Emperor Thaurissan",
                "Onyxia",
                "Deathwing",
                "Old Ironforge",
            ],
            "Alleria": [
                "Turalyon",
                "Locus-Walker",
                "Sylvanas Windrunner",
                "Vereesa Windrunner",
                "Nathanos Blightcaller",
                "Kil'jaeden",
                "The Void",
                "Xal'atath",
            ],
            "Faelin": [
                "Queen Azshara",
                "N'Zoth",
                "Blackwater Behemoth",
                "Ozumat",
                "Abyssal Commander",
                "Sunken Guardian",
                "Crabatoa",
                "The Leviathan",
            ],
            # ---------------------------------------------------------------
            # FIX: These heroes were previously in "other_adventures" whose
            # series_name = "Adventure Mode". Their YouTube titles correctly
            # say "Book of Heroes", so they belong here. Moving them into
            # book_of_heroes means ADVENTURE_DIRECTORY[mode]["series_name"]
            # returns "Book of Heroes" instead of "Adventure Mode".
            # ---------------------------------------------------------------
            "Medivh": [
                "Graves the Cleric",
                "Elder Brandlemar",
                "Russell the Bard",
                "Fungalmancer Flurgl",
            ],
            "Kel'Thuzad": [
                "Wee Whelp",
                "Overseer Mogark",
                "Frostfur",
                "George and Karl",
            ],
            "King Rastakhan": [
                "Giant Rat",
                "Candlebeard",
                "Seriona",
                "Blackseed",
                "Whompwhisker",
                "Chronomancer Inara",
                "King Togwaggle",
                "Bwonsamdi",
            ],
            "Chef Scabbs": [
                "Gutmook",
            ],
            "Rikkar": [
                "High Priest Thekal",
            ],
        },
    },
    "book_of_mercenaries": {
        "series_name": "Book of Mercenaries",
        "heroes": {
            "Rokara": [
                "Bru'kan",
                "Herzul Bloodmark",
                "Dread Rider Cullen",
                "Apothecary Helbrim",
                "Mankrik",
                "Mutanus",
                "Xyrella",
                "Garrosh Hellscream",
            ],
            "Xyrella": [
                "Kresh",
                "Tavish Stormpike",
                "Rokara",
                "Shadowed Spirit",
                "Mutanus",
                "Scabbs Cutterbutter",
                "Tamsin Roame",
                "Garona Halforcen",
            ],
            "Guff": [
                "Angry Treant",
                "Kolkar Pack Runner",
                "Razormane Battleguard",
                "Bristleback Knight",
                "Boulderfist Oger",
                "Lady Anacondra",
                "Mutanus",
                "Cannonmaster Smythe",
            ],
            "Kurtrus": [
                "Illidari Student",
                "Rustwix",
                "Soulbinder",
                "Mo'arg Outcast",
                "Anetheron",
                "Tamsin Roame",
                "Xyrella",
                "Neeru Fireblade",
            ],
            "Tamsin": [
                "Wailing Banshee",
                "Murloc Tidecaller",
                "Devouring Ectoplasm",
                "Mutanus",
                "Cornelius Roame",
                "Cariel Roame",
                "Lord Godfrey",
                "Anetheron",
            ],
            "Cariel": [
                "Northwatch Grunt",
                "Rokara",
                "Guff Runetotem",
                "Tamsin Roame",
                "Kurtrus Ashfallen",
                "Xyrella",
                "Cornelius Roame",
                "Lightforged Cariel Finale",
            ],
            "Scabbs": [
                "SI:7 Trainee",
                "Rokara",
                "Tavish Stormpike",
                "Vanessa VanCleef",
                "Mr. Smite",
                "Edwin VanCleef",
                "Xyrella",
                "Kazakus",
            ],
            "Tavish": [
                "Bristleback Tracker",
                "Rokara",
                "Guff Runetotem",
                "Mutanus",
                "King Krush",
                "Scabbs Cutterbutter",
                "Bru'kan",
                "Vanndar Stormpike",
            ],
            "Bru'kan": [
                "Rokara",
                "Guff Runetotem",
                "Elemental Conduit",
                "Barrens Invader",
                "Tamsin Roame",
                "Cornelius Roame",
                "Tavish Stormpike",
                "Galvangar",
            ],
            "Varden": [
                "Frost Apprentice",
                "Xyrella",
                "Cariel Roame",
                "Tamsin Roame",
                "Scabbs Cutterbutter",
                "Bru'kan",
                "Rokara",
                "Drek'Thar",
            ],
        },
    },
    # -----------------------------------------------------------------------
    # "other_adventures" now only contains heroes whose YouTube titles
    # genuinely say "Adventure Mode" in the series slot (not Book of Heroes).
    # Nemesis Gul'dan uses the Nemesis adventure branding.
    # -----------------------------------------------------------------------
    "other_adventures": {
        "series_name": "Adventure Mode",
        "heroes": {
            "Nemesis Gul'dan": [
                "Opera Diva Tamsin",
                "Mecha-Jaraxxus",
                "N'Zoth",
            ],
            "Pathmaker Hamm": [
                "Bristlesnarl",
            ],
        },
    },
}

ALIASES = {
    # Core normalization (punctuation, casing)
    "guldan": "Gul'dan",
    "guldans": "Gul'dan",
    "kelthuzad": "Kel'Thuzad",
    "kel thuzad": "Kel'Thuzad",
    "nzoth": "N'Zoth",
    "n zoth": "N'Zoth",
    "nzoths": "N'Zoth",

    # Multi-entity / duo
    "george": "George and Karl",
    "karl": "George and Karl",
    "george and karl": "George and Karl",

    # Mercenaries name normalization
    "brukan": "Bru'kan",
    "brukan the shaman": "Bru'kan",
    "varden dawngrasp": "Varden",
    "scabbs cutterbutter": "Scabbs",
    "kurtrus ashfallen": "Kurtrus",
    "guff runetotem": "Guff",
    "xyrella": "Xyrella",
    "rokara": "Rokara",
    "tamsin roame": "Tamsin",
    "cariel roame": "Cariel",

    # Common title-style variants
    "king rastakhan": "King Rastakhan",
    "nemesis guldan": "Nemesis Gul'dan",
    "pathmaker hamm": "Pathmaker Hamm",
    "chef scabbs": "Chef Scabbs",
    "Garrosh of Wrath": "garrosh" 

    # Frequent Whisper-style mis-hearings
    "rag naros": "Ragnaros",
    "ragna ros": "Ragnaros",
    "flurgo": "Fungalmancer Flurgl",
    "fungalmancer flurgo": "Fungalmancer Flurgl",
    "arthas menithil": "Arthas Menethil",
    "annetheron": "Anetheron",
    "khaelthas": "Kael'thas Sunstrider",
    "kaelthas": "Kael'thas Sunstrider",
    "illidan storm rage": "Illidan Stormrage",

    # Book of Heroes heroes that appear in title blobs
    "medivh": "Medivh",
    "kel'thuzad": "Kel'Thuzad",
    "rastakhan": "King Rastakhan",
    "chef scabbs": "Chef Scabbs",
    "rikkar": "Rikkar",
}
