ADVENTURE_DIRECTORY = {
    "book_of_heroes": {
        "series_name": "Book of Heroes",
        "heroes": {
            "Jaina": ["Arthas Menethil", "Antonidas", "Aegwynn", "Archmage Kalec", "The Lich King"],
            "Rexxar": ["Leoroxx", "Warchief Blackhand", "Misha", "Ferocious Quilboar", "Lady Darkscale", "Khiragg", "Daelin Proudmoore", "Gorgrom the Dragon-Eater"],
            "Garrosh": ["Greatmother Geyah", "Rehgar Earthfury", "Underqueen Zarzhet", "Seering Fire Elemental", "Cairne Bloodhoof", "Jaina Proudmoore", "Anduin Wrynn", "Thrall"],
            "Uther": ["Alonsus Faol", "Orgrim Doomhammer", "Varok Saurfang", "The Dark Portal", "Blackrock Blademaster", "Venim Iceblade", "Mal'Ganis", "Prince Arthas"],
            "Valeera": ["Hogger", "Edwin VanCleef", "Baron Revilgaz", "The Medics", "Trade Prince Gallywix", "Cho'Gall", "Garona Halforcen", "King Varian Wrynn"],
            "Anduin": ["King Varian Wrynn", "Prophet Velen", "Archbishop Benedictus", "Valithria Dreamwalker", "Gul'dan", "Garrosh Hellscream", "Sylvanas Windrunner", "The Jailer"],
            "Thrall": ["Durotan", "Draka", "Grommash Hellscream", "Orgrim Doomhammer", "Blackmoore", "Jaina Proudmoore", "Garrosh Hellscream", "Deathwing"],
            "Gul'dan": ["Ner'zhul", "Cho'gall", "Blackhand", "Doomhammer", "Kil'jaeden", "Mannoroth", "Medivh", "Illidan Stormrage"],
            "Malfurion": ["Cenarius", "Xavius", "Malfurion's Nightmare", "Azshara", "Mannoroth", "Archimonde", "Illidan Stormrage", "Ysera"],
            "Illidan": ["Kurtrus Ashfallen", "Azshara", "Akama", "Maiev Shadowsong", "Kael'thas Sunstrider", "Malfurion Stormrage", "Sargeras", "Arthas"],
            "Magni": ["Muradin Bronzebeard", "Moira Bronzebeard", "Ragnaros", "Nefarian", "Emperor Thaurissan", "Onyxia", "Deathwing", "Old Ironforge"],
            "Alleria": ["Turalyon", "Locus-Walker", "Sylvanas Windrunner", "Vereesa Windrunner", "Nathanos Blightcaller", "Kil'jaeden", "The Void", "Xal'atath"],
            "Faelin": ["Queen Azshara", "N'Zoth", "Blackwater Behemoth", "Ozumat", "Abyssal Commander", "Sunken Guardian", "Crabatoa", "The Leviathan"],
        },
    },
    "book_of_mercenaries": {
        "series_name": "Book of Mercenaries",
        "heroes": {
            "Rokara": ["Bru'kan", "Herzul Bloodmark", "Dread Rider Cullen", "Apothecary Helbrim", "Mankrik", "Mutanus", "Xyrella", "Garrosh Hellscream"],
            "Xyrella": ["Kresh", "Tavish Stormpike", "Rokara", "Shadowed Spirit", "Mutanus", "Scabbs Cutterbutter", "Tamsin Roame", "Garona Halforcen"],
            "Guff": ["Angry Treant", "Kolkar Pack Runner", "Razormane Battleguard", "Bristleback Knight", "Boulderfist Oger", "Lady Anacondra", "Mutanus", "Cannonmaster Smythe"],
            "Kurtrus": ["Illidari Student", "Rustwix", "Soulbinder", "Mo'arg Outcast", "Anetheron", "Tamsin Roame", "Xyrella", "Neeru Fireblade"],
            "Tamsin": ["Wailing Banshee", "Murloc Tidecaller", "Devouring Ectoplasm", "Mutanus", "Cornelius Roame", "Cariel Roame", "Lord Godfrey", "Anetheron"],
            "Cariel": ["Northwatch Grunt", "Rokara", "Guff Runetotem", "Tamsin Roame", "Kurtrus Ashfallen", "Xyrella", "Cornelius Roame", "Lightforged Cariel Finale"],
            "Scabbs": ["SI:7 Trainee", "Rokara", "Tavish Stormpike", "Vanessa VanCleef", "Mr. Smite", "Edwin VanCleef", "Xyrella", "Kazakus"],
            "Tavish": ["Bristleback Tracker", "Rokara", "Guff Runetotem", "Mutanus", "King Krush", "Scabbs Cutterbutter", "Bru'kan", "Vanndar Stormpike"],
            "Bru'kan": ["Rokara", "Guff Runetotem", "Elemental Conduit", "Barrens Invader", "Tamsin Roame", "Cornelius Roame", "Tavish Stormpike", "Galvangar"],
            "Varden": ["Frost Apprentice", "Xyrella", "Cariel Roame", "Tamsin Roame", "Scabbs Cutterbutter", "Bru'kan", "Rokara", "Drek'Thar"],
        },
    },
    "other_adventures": {
        "series_name": "Adventure Mode",
        "heroes": {
            "Medivh": ["Graves the Cleric", "Elder Brandlemar", "Russell the Bard", "Fungalmancer Flurgl"],
            "Kel'Thuzad": ["Wee Whelp", "Overseer Mogark", "Frostfur", "George and Karl"],
            "King Rastakhan": ["Giant Rat", "Candlebeard", "Seriona", "Blackseed", "Whompwhisker", "Chronomancer Inara", "King Togwaggle", "Bwonsamdi"],
            "Chef Scabbs": ["Gutmook"],
            "Rikkar": ["High Priest Thekal"],
            "Nemesis Gul'dan": ["Opera Diva Tamsin", "Mecha-Jaraxxus", "N'Zoth"],
            "Pathmaker Hamm": ["Bristlesnarl"],
        },
    },
}

ALIASES = {
    "guldan": "Gul'dan",
    "kelthuzad": "Kel'Thuzad",
    "nzoth": "N'Zoth",
    "george": "George and Karl",
    "karl": "George and Karl",
    "brukan": "Bru'kan",
    "varden dawngrasp": "Varden",
    "scabbs cutterbutter": "Scabbs",
    "kurtrus ashfallen": "Kurtrus",
    "guff runetotem": "Guff",
    "xyrella": "Xyrella",
    "rokara": "Rokara",
    "tamsin roame": "Tamsin",
    "cariel roame": "Cariel",
}
